let words=[],pictures=[],pictureRound=[],mode='list',index=0,revealed=false,answered=false,score=0,total=0,quizChoices=[];
const $=s=>document.querySelector(s),surface=$('#surface');
const sentenceQuestions=[
  {q:'こうえんに こどもが ______ います。',a:'たくさん',choices:['たくさん','ぜんぶ','あまり','よく'],note:'「たくさん」 indica grande quantidade. 「ぜんぶ」 significa “todos” ou “tudo”.'},
  {q:'りんごは ３こ ______ ６レアルです。',a:'で',choices:['で','の','と','に'],note:'Para dizer o preço de uma quantidade, usamos 「３こで６レアル」: três unidades por seis reais.'},
  {q:'この まちは ______ では ありません。',a:'しずか',choices:['しずか','おいしい','あつい','ふるい'],note:'Na forma negativa de um adjetivo な, usamos 「しずかではありません」.'},
  {q:'わたしは さんすうが ______ では ありません。',a:'きらい',choices:['きらい','あつい','ながい','おいしい'],note:'「きらいではありません」 significa “não detesto” ou “não desgosto”.'},
  {q:'やすみは １０がつ３にち ______ です。',a:'まで',choices:['まで','に','と','へ'],note:'「まで」 indica o último dia ou o limite de um período.'},
  {q:'「これは マリアさんの ほんですか。」「いいえ、______ です。」',a:'わたしの',choices:['わたしの','わたし','だれ','どこ'],note:'「の」 retoma o objeto já mencionado: 「わたしの」 significa “é meu”.'},
  {q:'この へやは ______ です。',a:'ひろい',choices:['ひろい','よく','ぜんぶ','たくさん'],note:'「ひろい」 é um adjetivo い que descreve o tamanho da sala.'},
  {q:'わたしは サッカーが ______ です。',a:'すき',choices:['すき','あつい','あかるい','ながい'],note:'Para dizer que gosta de algo, usamos 「～が すきです」.'},
  {q:'ねこは つくえの ______ います。',a:'したに',choices:['したに','したを','したで','したへ'],note:'Para indicar onde alguém ou algum animal está, usamos 「～に います」.'},
  {q:'きょうしつに せいとが ３______ います。',a:'にん',choices:['にん','こ','まい','ほん'],note:'Para contar pessoas, usamos 「３にん」: três pessoas.'},
  {q:'バス ______ がっこうへ いきます。',a:'で',choices:['で','に','を','が'],note:'Para indicar o meio de transporte, usamos a partícula 「で」: 「バスで」.'},
  {q:'スーパーで トマト ______ かいます。',a:'を',choices:['を','が','に','で'],note:'Para indicar o que compramos, usamos 「を」: 「トマトを かいます」.'},
  {q:'「えきは どこですか。」「ぎんこうの ______ です。」',a:'まえ',choices:['まえ','あした','あさ','きのう'],note:'「まえ」 indica localização: em frente ao banco.'},
  {q:'「この ほんは だれのですか。」「______ です。」',a:'せんせいの',choices:['せんせいの','せんせいを','せんせいに','せんせいで'],note:'「せんせいの」 significa “do professor” e indica o dono do livro.'},
  {q:'「ケーキは いくらですか。」「______ です。」',a:'１０レアル',choices:['１０レアル','１０にん','１０じ','１０がつ'],note:'「いくら」 pergunta o preço; a resposta deve ser um valor em dinheiro.'},
  {q:'がっこうは げつようび ______ きんようびまで あります。',a:'から',choices:['から','まで','より','で'],note:'O período de início a fim é expresso por 「～から ～まで」.'},
  {q:'「あしたは なんようびですか。」「______ です。」',a:'かようび',choices:['かようび','あさごはん','きょうしつ','あか'],note:'「なんようび」 pergunta o dia da semana. A resposta é 「かようび」, terça-feira.'},
  {q:'「おにぎりを たべますか。」「いいえ、______。」',a:'たべません',choices:['たべません','たべます','たべました','たべもの'],note:'Depois de 「いいえ」, usamos a forma negativa: 「たべません」.'},
  {q:'「コップは どこに ありますか。」「テーブルの うえ ______ あります。」',a:'に',choices:['に','を','が','へ'],note:'Para indicar onde um objeto está, usamos 「～に あります」.'},
  {q:'「きょう、だれと かえりますか。」「ともだち ______ かえります。」',a:'と',choices:['と','を','に','で'],note:'Para indicar com quem fazemos algo, usamos a partícula 「と」.'}
];
const adjectiveQuestions=[
  {q:'O bolo é gostoso.',a:'この ケーキは おいしいです。',choices:['この ケーキは おいしいです。','この ケーキは おいしくないです。','この ケーキは おいしいでは ありません。','この ケーキは おいしくです。'],note:'Frase afirmativa com adjetivo い: 「おいしいです」.'},
  {q:'O bolo não é gostoso.',a:'この ケーキは おいしくないです。',choices:['この ケーキは おいしくないです。','この ケーキは おいしいです。','この ケーキは おいしいでは ありません。','この ケーキは おいしくです。'],note:'Frase negativa com adjetivo い: 「おいしい」 muda para 「おいしくないです」.'},
  {q:'Hoje está frio.',a:'きょうは さむいです。',choices:['きょうは さむいです。','きょうは さむくないです。','きょうは さむいでは ありません。','きょうは さむくです。'],note:'Frase afirmativa com adjetivo い: 「さむいです」.'},
  {q:'Hoje não está frio.',a:'きょうは さむくないです。',choices:['きょうは さむくないです。','きょうは さむいです。','きょうは さむいでは ありません。','きょうは さむくです。'],note:'Frase negativa com adjetivo い: 「さむい」 muda para 「さむくないです」.'},
  {q:'Este livro é novo.',a:'この ほんは あたらしいです。',choices:['この ほんは あたらしいです。','この ほんは あたらしくないです。','この ほんは あたらしいでは ありません。','この ほんは あたらしくです。'],note:'Frase afirmativa com adjetivo い: 「あたらしいです」.'},
  {q:'Este livro não é novo.',a:'この ほんは あたらしくないです。',choices:['この ほんは あたらしくないです。','この ほんは あたらしいです。','この ほんは あたらしいでは ありません。','この ほんは あたらしくです。'],note:'Frase negativa com adjetivo い: 「あたらしい」 muda para 「あたらしくないです」.'},
  {q:'A sala é silenciosa.',a:'この へやは しずかです。',choices:['この へやは しずかです。','この へやは しずかでは ありません。','この へやは しずかいです。','この へやは しずかくないです。'],note:'Frase afirmativa com adjetivo な: 「しずかです」.'},
  {q:'A sala não é silenciosa.',a:'この へやは しずかでは ありません。',choices:['この へやは しずかでは ありません。','この へやは しずかです。','この へやは しずかいです。','この へやは しずかくないです。'],note:'Frase negativa com adjetivo な: 「しずかでは ありません」.'},
  {q:'O quarto é bonito.',a:'この へやは きれいです。',choices:['この へやは きれいです。','この へやは きれいでは ありません。','この へやは きれいいです。','この へやは きれいくないです。'],note:'「きれい」 é um adjetivo な. Na frase afirmativa: 「きれいです」.'},
  {q:'O quarto não é bonito.',a:'この へやは きれいでは ありません。',choices:['この へやは きれいでは ありません。','この へやは きれいです。','この へやは きれいいです。','この へやは きれいくないです。'],note:'「きれい」 é um adjetivo な. Na frase negativa: 「きれいでは ありません」.'},
  {q:'Eu gosto de futebol.',a:'わたしは サッカーが すきです。',choices:['わたしは サッカーが すきです。','わたしは サッカーが すきでは ありません。','わたしは サッカーが すきいです。','わたしは サッカーが すきくないです。'],note:'「すき」 é um adjetivo な. Na frase afirmativa: 「すきです」.'},
  {q:'Eu não gosto de futebol.',a:'わたしは サッカーが すきでは ありません。',choices:['わたしは サッカーが すきでは ありません。','わたしは サッカーが すきです。','わたしは サッカーが すきいです。','わたしは サッカーが すきくないです。'],note:'Frase negativa com 「すき」: 「すきでは ありません」.'},
  {q:'Este livro é bom.',a:'この ほんは いいです。',choices:['この ほんは いいです。','この ほんは よくないです。','この ほんは いいでは ありません。','この ほんは よくです。'],note:'Frase afirmativa com 「いい」: 「いいです」.'},
  {q:'Este livro não é bom.',a:'この ほんは よくないです。',choices:['この ほんは よくないです。','この ほんは いいです。','この ほんは いいくないです。','この ほんは いいでは ありません。'],note:'「いい」 é irregular na forma negativa: 「よくないです」.'}
];
const categoryPT={"い形容詞": "Adjetivos い", "な形容詞": "Adjetivos な", "スポーツ": "Esportes", "乗り物": "Transportes", "人・家族": "Pessoas e família", "位置・方向": "Posição e direção", "体": "Partes do corpo", "副詞": "Advérbios", "動物": "Animais", "国・言語": "Países e idiomas", "場所・建物": "Lugares e edifícios", "学校・勉強": "Escola e estudos", "家のもの": "Objetos de casa", "時間・曜日": "Horas e dias da semana", "服・身につけるもの": "Roupas e acessórios", "色": "Cores", "身の回り・その他": "Objetos do dia a dia e outros", "食べ物・飲み物": "Comidas e bebidas"};
const typePT={'名詞':'Substantivos','い形容詞':'Adjetivos い','な形容詞':'Adjetivos な','副詞':'Advérbios'};
const random=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>{const copy=[...a];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
function filtered(){let t=$('#type').value,c=$('#category').value,q=$('#search').value.trim().toLocaleLowerCase();return words.filter(w=>(t==='all'||w.type===t)&&(c==='all'||w.category===c)&&(!q||w.term.toLocaleLowerCase().includes(q)||w.pt.toLocaleLowerCase().includes(q)))}
function setCategories(){let current=$('#category').value,t=$('#type').value;let cats=[...new Set(words.filter(w=>t==='all'||w.type===t).map(w=>w.category))].sort((a,b)=>a.localeCompare(b,'ja'));$('#category').innerHTML='<option value="all">Todas</option>'+cats.map(c=>`<option value="${escapeHTML(c)}">${escapeHTML(categoryPT[c]||c)}</option>`).join('');$('#category').value=cats.includes(current)?current:'all'}
function escapeHTML(s){return s.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function list(){let a=filtered();$('#status').textContent=`${a.length} palavras`;if(!a.length){surface.innerHTML='<div class="empty">Nenhuma palavra encontrada.</div>';return}let html='';for(const level of ['NM4','NM5']){const levelWords=a.filter(w=>w.level===level);if(!levelWords.length)continue;html+=`<h2 class="group-title">${level==='NM5'?'Revisão NM5':'NM4'} <small>${levelWords.length} palavras</small></h2>`;for(const cat of [...new Set(levelWords.map(w=>w.category))].sort((x,y)=>x.localeCompare(y,'ja'))){const group=levelWords.filter(w=>w.category===cat);html+=`<h3 class="category-title">${escapeHTML(categoryPT[cat]||cat)} <small>${group.length}</small></h3><div class="grid">${group.map(w=>`<article class="word"><div class="meta">${escapeHTML(typePT[w.type]||w.type)}</div><strong lang="ja">${escapeHTML(w.term)}</strong><div class="pt" lang="pt-BR">${escapeHTML(w.pt)}</div></article>`).join('')}</div>`}}surface.innerHTML=html}
function card(){let a=filtered();if(!a.length){$('#status').textContent='0 palavras';surface.innerHTML='<div class="empty">Altere os filtros para encontrar palavras.</div>';return}index%=a.length;let w=a[index];$('#status').textContent=`Palavra ${index+1} de ${a.length}`;surface.innerHTML=`<div class="panel card-panel"><div class="card-head"><span class="pill">${w.level} · ${escapeHTML(categoryPT[w.category]||w.category)}</span><span class="card-count">${index+1} / ${a.length}</span></div><button class="card-face ${revealed?'is-revealed':''}" id="flip" aria-label="${revealed?'Ver palavra em japonês':'Ver tradução de '+escapeHTML(w.term)}"><span class="card-face-label">${revealed?'Tradução':'Japonês'}</span><strong lang="${revealed?'pt-BR':'ja'}">${revealed?escapeHTML(w.pt):escapeHTML(w.term)}</strong><span class="flip-hint">${revealed?'↶ Ver palavra':'↶ Virar cartão'}</span></button><div class="row card-actions"><button class="action secondary" id="next">Próxima palavra →</button></div></div>`;$('#flip').onclick=()=>{revealed=!revealed;card()};$('#next').onclick=()=>{index++;revealed=false;card()}}
function wordQuiz(){let a=filtered();if(a.length<4){$('#status').textContent='';surface.innerHTML='<div class="empty">O quiz precisa de pelo menos quatro palavras. Amplie os filtros.</div>';return}index%=a.length;let w=a[index];if(!quizChoices.length)quizChoices=shuffle([w,...shuffle(a.filter(x=>x.pt!==w.pt)).slice(0,3)]);$('#status').textContent=`${index+1} / ${a.length} palavras · Acertos: ${score} / ${total}`;surface.innerHTML=`<div class="panel"><span class="pill">${w.level} · ${escapeHTML(categoryPT[w.category]||w.category)}</span><div class="prompt" lang="ja">${escapeHTML(w.term)}</div><div class="choices">${quizChoices.map((c,i)=>`<button class="choice ${answered?(c.pt===w.pt?'correct':c===quizChoices.selected?'wrong':''):''}" data-i="${i}" ${answered?'disabled':''} lang="pt-BR">${escapeHTML(c.pt)}</button>`).join('')}</div>${answered?`<div class="explain">${quizChoices.selected?.pt===w.pt?'Acertou!':'Resposta: '+escapeHTML(w.pt)}</div><div class="row"><button class="action" id="next">Próximo</button></div>`:''}</div>`;if(answered){$('#next').onclick=()=>{index++;answered=false;quizChoices=[];wordQuiz()}}else surface.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{quizChoices.selected=quizChoices[+b.dataset.i];answered=true;total++;if(quizChoices.selected.pt===w.pt)score++;wordQuiz()})}
function pictureQuiz(){if(!pictures.length){surface.innerHTML='<div class="empty">Carregando imagens...</div>';return}if(!pictureRound.length)pictureRound=shuffle(pictures);if(index>=pictureRound.length){$('#status').textContent='Concluído';surface.innerHTML=`<div class="panel"><span class="pill">NM4 · Quiz com imagens</span><div class="prompt">${score} / ${pictureRound.length} acertos</div><div class="row"><button class="action" id="restart">Tentar novamente</button></div></div>`;$('#restart').onclick=()=>{index=0;score=total=0;answered=false;quizChoices=[];pictureRound=shuffle(pictures);pictureQuiz()};return}const q=pictureRound[index];if(!quizChoices.length){const related=pictures.filter(x=>x.term!==q.term&&x.group===q.group);const others=pictures.filter(x=>x.term!==q.term&&x.group!==q.group);quizChoices=shuffle([q,...shuffle(related).slice(0,3),...shuffle(others).slice(0,Math.max(0,3-related.length))])}$('#status').textContent=`${index+1} / ${pictureRound.length} questões · Acertos: ${score} / ${total}`;surface.innerHTML=`<div class="panel picture-panel"><span class="pill">NM4 · Olhe a imagem e escolha</span><p class="instruction">Como se chama esta imagem em japonês?</p><div class="picture-frame"><img src="${escapeHTML(q.image)}" alt="Imagem para escolher o nome em japonês" loading="eager"></div><div class="choices">${quizChoices.map((v,i)=>`<button class="choice ${answered?(v.term===q.term?'correct':v===quizChoices.selected?'wrong':''):''}" data-i="${i}" ${answered?'disabled':''} lang="ja">${escapeHTML(v.term)}</button>`).join('')}</div>${answered?`<div class="explain">${quizChoices.selected?.term===q.term?'Acertou!':'Resposta: '+escapeHTML(q.term)} <span lang="pt-BR">(${escapeHTML(q.pt)})</span></div><div class="row"><button class="action" id="next">${index===pictureRound.length-1?'Ver resultado':'Próximo'}</button></div>`:''}</div>`;if(answered){$('#next').onclick=()=>{index++;answered=false;quizChoices=[];pictureQuiz()}}else surface.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{quizChoices.selected=quizChoices[+b.dataset.i];answered=true;total++;if(quizChoices.selected.term===q.term)score++;pictureQuiz()})}
function practiceQuiz(questions,label){if(index>=questions.length){$('#status').textContent='Concluído';surface.innerHTML=`<div class="panel"><span class="pill">${label}</span><div class="prompt">${score} / ${questions.length} acertos</div><div class="row"><button class="action" id="restart">Tentar novamente</button></div></div>`;$('#restart').onclick=()=>{index=0;answered=false;score=total=0;quizChoices=[];practiceQuiz(questions,label)};return}let q=questions[index];if(!quizChoices.length)quizChoices=shuffle(q.choices);$('#status').textContent=`${index+1} / ${questions.length} questões · Acertos: ${score} / ${total}`;surface.innerHTML=`<div class="panel"><span class="pill">${label}</span>${mode==='adjectives'?'<p class="instruction">Escolha a frase em japonês que corresponde ao português.</p>':''}<div class="prompt" lang="${mode==='adjectives'?'pt-BR':'ja'}">${escapeHTML(q.q)}</div><div class="choices">${quizChoices.map((v,i)=>`<button class="choice ${answered?(v===q.a?'correct':v===quizChoices.selected?'wrong':''):''}" data-i="${i}" ${answered?'disabled':''} lang="ja">${escapeHTML(v)}</button>`).join('')}</div>${answered?`<div class="explain">${quizChoices.selected===q.a?'Acertou!':'Resposta: '+escapeHTML(q.a)}<br>${escapeHTML(q.note)}</div><div class="row"><button class="action" id="next">${index===questions.length-1?'Ver resultado':'Próximo'}</button></div>`:''}</div>`;if(answered){$('#next').onclick=()=>{index++;answered=false;quizChoices=[];practiceQuiz(questions,label)}}else surface.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{quizChoices.selected=quizChoices[+b.dataset.i];answered=true;total++;if(quizChoices.selected===q.a)score++;practiceQuiz(questions,label)})}
function render(){if(mode==='list')list();if(mode==='cards')card();if(mode==='quiz')wordQuiz();if(mode==='pictures')pictureQuiz();if(mode==='sentences')practiceQuiz(sentenceQuestions,'Prática de frases');if(mode==='adjectives')practiceQuiz(adjectiveQuestions,'Frases com adjetivos')}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));$('#filters').hidden=['sentences','adjectives','pictures'].includes(mode);index=0;revealed=false;answered=false;score=total=0;quizChoices=[];pictureRound=[];render()});
['type','category','search'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',()=>{if(id==='type')setCategories();index=0;revealed=false;answered=false;score=total=0;quizChoices=[];render()}));
fetch('data.json').then(r=>{if(!r.ok)throw Error('data');return r.json()}).then(data=>{words=data;setCategories();render()}).catch(()=>{$('#status').textContent='Não foi possível carregar as palavras.';});
fetch('pictures.json').then(r=>{if(!r.ok)throw Error('pictures');return r.json()}).then(data=>{pictures=data;if(mode==='pictures')render()}).catch(()=>{if(mode==='pictures')surface.innerHTML='<div class="empty">Não foi possível carregar as imagens.</div>'});
